server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
      
  datasource:
#    url: jdbc:oracle:thin:@192.168.10.72:1521/orcl11
 #집에서 테스트할때는 아래의 주소로 해주세요
    url: jdbc:oracle:thin:@localhost:1521/orcl11
    username: itryp
    password: itryp0509
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 20000
      validation-timeout: 3000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      pool-name: oraPool
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 20MB
      
mybatis:
  mapper-locations: mapper/**/*.xml